const VOCAB_BANK = [
  // Verbs
  { en: "Adjust", th: "ปรับเปลี่ยน", type: "v" },
  { en: "Enable", th: "ทำให้สามารถ", type: "v" },
  { en: "Maintain", th: "บำรุงรักษา", type: "v" },
  { en: "Affect", th: "ส่งผลกระทบ", type: "v" },
  { en: "Appeal", th: "วิงวอน", type: "v" },
  { en: "Restore", th: "ฟื้นฟู", type: "v" },
  { en: "Suffer", th: "ทนทุกข์", type: "v" },
  { en: "Ensure", th: "ทำให้มั่นใจ", type: "v" },
  { en: "Alter", th: "เปลี่ยนแปลง", type: "v" },
  { en: "Cope", th: "รับมือ", type: "v" },
  { en: "Commit", th: "มุ่งมั่น", type: "v" },
  { en: "Assume", th: "ทึกทัก", type: "v" },
  { en: "Respond", th: "ตอบสนอง", type: "v" },
  { en: "Abandon", th: "ละทิ้ง", type: "v" },
  { en: "Betray", th: "ทรยศ", type: "v" },
  { en: "Collapse", th: "พังทลาย", type: "v" },
  { en: "Encounter", th: "เผชิญหน้า", type: "v" },
  { en: "Occur", th: "เกิดขึ้น", type: "v" },
  { en: "Classify", th: "แยกประเภท", type: "v" },
  { en: "Sail", th: "แล่นเรือ", type: "v" },
  { en: "Seek", th: "ค้นหา", type: "v" },
  { en: "Drown", th: "จมน้ำ", type: "v" },
  { en: "Determine", th: "กำหนด", type: "v" },
  { en: "Confirm", th: "ยืนยัน", type: "v" },
  { en: "Capture", th: "ยึดครอง", type: "v" },

  // Nouns
  { en: "Balance", th: "สมดุล", type: "n" },
  { en: "Current", th: "กระแสน้ำ", type: "n" },
  { en: "Anxiety", th: "ความวิตกกังวล", type: "n" },
  { en: "Treatment", th: "การรักษา", type: "n" },
  { en: "State", th: "สถานะ", type: "n" },
  { en: "Faith", th: "ศรัทธา", type: "n" },
  { en: "Infection", th: "การติดเชื้อ", type: "n" },
  { en: "Factor", th: "ปัจจัย", type: "n" },
  { en: "Needle", th: "เข็มฉีดยา", type: "n" },
  { en: "Expectation", th: "ความคาดหวัง", type: "n" },
  { en: "Strength", th: "จุดแข็ง", type: "n" },
  { en: "Institution", th: "สถาบัน", type: "n" },
  { en: "Association", th: "สมาคม", type: "n" },
  { en: "Award", th: "รางวัล", type: "n" },
  { en: "Weakness", th: "จุดอ่อน", type: "n" },
  { en: "Intention", th: "ความตั้งใจ", type: "n" },
  { en: "Circumstance", th: "สถานการณ์", type: "n" },
  { en: "Selection", th: "การคัดเลือก", type: "n" },
  { en: "Relief", th: "ความโล่งอก", type: "n" },
  { en: "Combination", th: "การผสมผสาน", type: "n" },
  { en: "Reputation", th: "ชื่อเสียง", type: "n" },
  { en: "Perspective", th: "มุมมอง", type: "n" },
  { en: "Pirate", th: "โจรสลัด", type: "n" },
  { en: "Feature", th: "คุณลักษณะ", type: "n" },
  { en: "Shipwreck", th: "ซากเรือแตก", type: "n" },
  { en: "Destination", th: "จุดหมาย", type: "n" },
  { en: "Voyage", th: "การเดินทางไกล", type: "n" },
  { en: "Port", th: "ท่าเรือ", type: "n" },

  // Adjectives
  { en: "Crucial", th: "สำคัญยิ่ง", type: "adj" },
  { en: "Conventional", th: "ตามแบบแผน", type: "adj" },
  { en: "Gradual", th: "ค่อยเป็นค่อยไป", type: "adj" },
  { en: "Practical", th: "ใช้ได้จริง", type: "adj" },
  { en: "Aware", th: "ตระหนัก", type: "adj" },
  { en: "Valid", th: "ถูกต้อง", type: "adj" },
  { en: "Medical", th: "ทางการแพทย์", type: "adj" },
  { en: "Potential", th: "ที่มีศักยภาพ", type: "adj" },
  { en: "Massive", th: "มหึมา", type: "adj" },
  { en: "Artificial", th: "เทียม", type: "adj" },
  { en: "Poisonous", th: "เป็นพิษ", type: "adj" },
  { en: "Competitive", th: "ชอบแข่งขัน", type: "adj" },
  { en: "Tough", th: "ยากลำบาก", type: "adj" },
  { en: "Sufficient", th: "เพียงพอ", type: "adj" },
  { en: "Deliberate", th: "เจตนา", type: "adj" },
  { en: "Outstanding", th: "โดดเด่น", type: "adj" },
  { en: "Overall", th: "โดยรวม", type: "adj" },
  { en: "Ideal", th: "ดีเลิศ", type: "adj" },
  { en: "Suspicious", th: "น่าสงสัย", type: "adj" },
  { en: "Proud", th: "ภูมิใจ", type: "adj" },
  { en: "Extensive", th: "กว้างขวาง", type: "adj" },
  { en: "Instant", th: "ทันที", type: "adj" },
  { en: "Attractive", th: "ดึงดูดใจ", type: "adj" },
  { en: "Stunning", th: "น่าทึ่ง", type: "adj" },
  { en: "Remarkable", th: "โดดเด่น", type: "adj" },
  { en: "Dreadful", th: "น่ากลัว", type: "adj" },
  { en: "Exotic", th: "แปลกตา", type: "adj" },
  { en: "Astonishing", th: "น่าทึ่งมาก", type: "adj" },
  { en: "Priceless", th: "ล้ำค่า", type: "adj" },
  { en: "Unsophisticated", th: "ไม่ซับซ้อน", type: "adj" },
  { en: "Tremendous", th: "ใหญ่โตมาก", type: "adj" },
  { en: "Insignificant", th: "ไม่สำคัญ", type: "adj" },
  { en: "Capable", th: "ที่สามารถทำได้", type: "adj" },

  // Adverbs
  { en: "Eventually", th: "ในที่สุด", type: "adv" },
  { en: "Initially", th: "ในตอนแรก", type: "adv" },
  { en: "Quite", th: "ค่อนข้างมาก", type: "adv" },
  { en: "Truly", th: "อย่างแท้จริง", type: "adv" },

  // Special Nouns
  { en: "Behalf", th: "ในนามของ", type: "n" },
];
