const VOCAB_BANK = [
  // กลุ่มคำกริยา (Verbs)
  { en: "Adjust", th: "plans", type: "v" },
  { en: "Enable", th: "coach", type: "v" },
  { en: "Maintain", th: "diet", type: "v" },
  { en: "Affect", th: "change", type: "v" },
  { en: "Restore", th: "return", type: "v" },
  { en: "Suffer", th: "experience", type: "v" },
  { en: "Ensure", th: "plenty", type: "v" },
  { en: "Cope", th: "responsibility", type: "v" },
  { en: "Commit", th: "attending", type: "v" },
  { en: "Assume", th: "cookies", type: "v" },
  { en: "Respond", th: "feedback", type: "v" },
  { en: "Abandon", th: "leave", type: "v" },
  { en: "Betray", th: "trusts you", type: "v" },
  { en: "Collapse", th: "break down", type: "v" },
  { en: "Encounter", th: "meeting", type: "v" },
  { en: "Occur", th: "happen", type: "v" },
  { en: "Classify", th: "scientists", type: "v" },
  { en: "Sail", th: "sunrise", type: "v" },
  { en: "Seek", th: "look for", type: "v" },
  { en: "Drown", th: "underwater", type: "v" },
  { en: "Determine", th: "decide", type: "v" },
  { en: "Confirm", th: "true", type: "v" },
  { en: "Capture", th: "control", type: "v" },

  // กลุ่มคำนาม (Nouns)
  { en: "Balance", th: "build", type: "n" },
  { en: "Current", th: "focus", type: "n" },
  { en: "Anxiety", th: "nervousness", type: "n" },
  { en: "Treatment", th: "medicines", type: "n" },
  { en: "Faith", th: "confidence", type: "n" },
  { en: "Infection", th: "skin", type: "n" },
  { en: "Factor", th: "routine", type: "n" },
  { en: "Needle", th: "Doctor", type: "n" },
  { en: "Strength", th: "deadline", type: "n" },
  { en: "Institution", th: "college", type: "n" },
  { en: "Capable", th: "very", type: "n" },
  { en: "Behalf", th: "staff", type: "n" },
  { en: "Association", th: "member", type: "n" },
  { en: "Award", th: "winning", type: "n" },
  { en: "Weakness", th: "small detail", type: "n" },
  { en: "Intention", th: "separate", type: "n" },
  { en: "Circumstance", th: "finish", type: "n" },
  { en: "Selection", th: "high number", type: "n" },
  { en: "Relief", th: "project", type: "n" },
  { en: "Combination", th: "together two", type: "n" },
  { en: "Reputation", th: "opinion", type: "n" },
  { en: "Perspective", th: "a way", type: "n" },
  { en: "Pirate", th: "captain", type: "n" },
  { en: "Feature", th: "amazing", type: "n" },
  { en: "Shipwreck", th: "lost", type: "n" },
  { en: "Destination", th: "traveling", type: "n" },
  { en: "Voyage", th: "long", type: "n" },
  { en: "Port", th: "ships", type: "n" },

  // กลุ่มคำคุณศัพท์ (Adjectives)
  { en: "Crucial", th: "most", type: "adj" },
  { en: "Conventional", th: "accepted", type: "adj" },
  { en: "Gradual", th: "moving", type: "adj" },
  { en: "Practical", th: "reasonable", type: "adj" },
  { en: "Medical", th: "team", type: "adj" },
  { en: "Potential", th: "diseases", type: "adj" },
  { en: "Massive", th: "biggest", type: "adj" },
  { en: "Competitive", th: "extremely", type: "adj" },
  { en: "Tough", th: "homework", type: "adj" },
  { en: "Sufficient", th: "candle", type: "adj" },
  { en: "Deliberate", th: "two hour", type: "adj" },
  { en: "Outstanding", th: "academic", type: "adj" },
  { en: "Overall", th: "improve", type: "adj" },
  { en: "Ideal", th: "relaxing", type: "adj" },
  { en: "Suspicious", th: "not trusting", type: "adj" },
  { en: "Proud", th: "well", type: "adj" },
  { en: "Extensive", th: "complete", type: "adj" },
  { en: "Instant", th: "very short", type: "adj" },
  { en: "Attractive", th: "interesting", type: "adj" },
  { en: "Stunning", th: "beautiful", type: "adj" },
  { en: "Remarkable", th: "coincidence", type: "adj" },
  { en: "Dreadful", th: "didn't like", type: "adj" },
  { en: "Exotic", th: "tried", type: "adj" },
  { en: "Astonishing", th: "absolutely", type: "adj" },
  { en: "Priceless", th: "decades", type: "adj" },
  { en: "Unsophisticated", th: "simple", type: "adj" },
  { en: "Tremendous", th: "large", type: "adj" },
  { en: "Insignificant", th: "unimportant", type: "adj" },

  // กลุ่มคำวิเศษณ์ (Adverbs)
  { en: "Initially", th: "my new", type: "adv" },
  { en: "Quite", th: "a lot", type: "adv" },
  { en: "Truly", th: "performance", type: "adv" },
];
