const VOCAB_BANK = [
  // กลุ่มคำกริยา (Verbs)
  { en: "Adjust (v.)", th: "ปรับเปลี่ยน", ex: "You need to adjust your strategy to hit the goal.", ex_th: "คุณต้องปรับเปลี่ยนกลยุทธ์เพื่อให้บรรลุเป้าหมาย" },
  { en: "Enable (v.)", th: "มอบอำนาจ/ทำให้สามารถ", ex: "The new system will enable the staff to work remotely.", ex_th: "ระบบใหม่จะมอบอำนาจให้พนักงานสามารถทำงานจากระยะไกลได้" },
  { en: "Maintain (v.)", th: "บำรุงรักษา/คงไว้", ex: "It is essential to maintain the equipment regularly.", ex_th: "จำเป็นอย่างยิ่งที่จะต้องบำรุงรักษาอุปกรณ์อย่างสม่ำเสมอ" },
  { en: "Affect (v.)", th: "ส่งผลกระทบ", ex: "Rising costs will affect our annual budget.", ex_th: "ค่าใช้จ่ายที่เพิ่มขึ้นจะส่งผลกระทบต่องบประมาณประจำปีของเรา" },
  { en: "Appeal (v.)", th: "วิงวอน/ดึงดูด", ex: "The charity had to appeal for urgent donations.", ex_th: "องค์กรการกุศลต้องวิงวอนขอเงินบริจาคอย่างเร่งด่วน" },
  { en: "Restore (v.)", th: "ฟื้นฟู", ex: "The government plans to restore the historic building.", ex_th: "รัฐบาลมีแผนที่จะฟื้นฟูอาคารประวัติศาสตร์แห่งนี้" },
  { en: "Suffer (v.)", th: "ทนทุกข์ทรมาน", ex: "The crops suffer from the lack of rain this season.", ex_th: "พืชผลต้องทนทุกข์ทรมานจากการขาดแคลนฝนในฤดูกาลนี้" },
  { en: "Ensure (v.)", th: "ทำให้มั่นใจ", ex: "Please check the data to ensure accuracy.", ex_th: "กรุณาตรวจสอบข้อมูลเพื่อให้มั่นใจในความถูกต้อง" },
  { en: "Alter (v.)", th: "เปลี่ยนแปลง", ex: "We had to alter the schedule due to the delay.", ex_th: "เราต้องเปลี่ยนแปลงตารางเวลาเนื่องจากความล่าช้า" },
  { en: "Cope (v.)", th: "รับมือ", ex: "She needs to find a way to cope with the stress.", ex_th: "เธอต้องหาวิธีรับมือกับความเครียด" },
  { en: "Commit (v.)", th: "มุ่งมั่น/ผูกมัด", ex: "We must commit to finishing this project on time.", ex_th: "เราต้องมุ่งมั่นที่จะทำโปรเจกต์นี้ให้เสร็จตรงเวลา" },
  { en: "Assume (v.)", th: "ทึกทัก/สมมุติ", ex: "Don't assume you know the answer without checking.", ex_th: "อย่าทึกทักว่ารู้คำตอบโดยไม่ได้ตรวจสอบ" },
  { en: "Respond (v.)", th: "ตอบสนอง", ex: "Please respond to my email as soon as possible.", ex_th: "กรุณาตอบสนองต่ออีเมลของฉันโดยเร็วที่สุด" },
  { en: "Abandon (v.)", th: "ละทิ้ง", ex: "They had to abandon the plan due to lack of funds.", ex_th: "พวกเขาต้องละทิ้งแผนเนื่องจากขาดเงินทุน" },
  { en: "Betray (v.)", th: "ทรยศ", ex: "He would never betray his friend's trust.", ex_th: "เขาจะไม่มีทางทรยศต่อความไว้ใจของเพื่อน" },
  { en: "Collapse (v.)", th: "พังทลาย", ex: "The old building may collapse in the earthquake.", ex_th: "อาคารเก่าอาจพังทลายลงในแผ่นดินไหว" },
  { en: "Encounter (v.)", th: "เผชิญหน้า/พบเจอ", ex: "We may encounter some problems along the way.", ex_th: "เราอาจพบเจอปัญหาบางอย่างระหว่างทาง" },
  { en: "Occur (v.)", th: "เกิดขึ้น", ex: "The accident occurred early in the morning.", ex_th: "อุบัติเหตุเกิดขึ้นในช่วงเช้าตรู่" },
  { en: "Classify (v.)", th: "แยกประเภทจัดกลุ่ม", ex: "Scientists classify animals based on their characteristics.", ex_th: "นักวิทยาศาสตร์แยกประเภทจัดกลุ่มสัตว์ตามลักษณะของพวกมัน" },
  { en: "Sail (v.)", th: "แล่นเรือ", ex: "We plan to sail around the island tomorrow.", ex_th: "เราวางแผนที่จะแล่นเรือรอบเกาะในวันพรุ่งนี้" },
  { en: "Seek (v.)", th: "ค้นหา", ex: "Many people seek happiness in their careers.", ex_th: "หลายคนค้นหาความสุขในอาชีพการงานของตน" },
  { en: "Drown (v.)", th: "จมน้ำ", ex: "He almost drown while swimming in the rough sea.", ex_th: "เขาเกือบจมน้ำขณะว่ายอยู่ในทะเลที่มีคลื่นแรง" },
  { en: "Determine (v.)", th: "ตัดสินใจแน่วแน่/กำหนด", ex: "We need to determine the root cause of the problem.", ex_th: "เราต้องกำหนดสาเหตุที่แท้จริงของปัญหา" },
  { en: "Confirm (v.)", th: "ยืนยัน", ex: "Please call the hotel to confirm your reservation.", ex_th: "กรุณาโทรไปที่โรงแรมเพื่อยืนยันการจองของคุณ" },
  { en: "Capture (v.)", th: "จับกุม/ยึดครอง", ex: "The photographer tried to capture the beauty of the sunset.", ex_th: "ช่างภาพพยายามที่จะบันทึกภาพความงามของพระอาทิตย์ตก" },
  { en: "Monitor (v.)", th: "เฝ้าสังเกต/ตรวจสอบ", ex: "Doctors need to monitor the patient's condition closely.", ex_th: "แพทย์ต้องเฝ้าสังเกตอาการของผู้ป่วยอย่างใกล้ชิด" },

  // กลุ่มคำนาม (Nouns)
  { en: "Balance (n.)", th: "สมดุล", ex: "It is important to keep a healthy work-life balance.", ex_th: "เป็นเรื่องสำคัญที่จะต้องรักษาสมดุลระหว่างชีวิตและการทำงานให้ดี" },
  { en: "Current (n.)", th: "ปัจจุบัน/กระแสน้ำ", ex: "We are focusing on current market demands.", ex_th: "เรากำลังมุ่งเน้นไปที่ความต้องการของตลาดในปัจจุบัน" },
  { en: "Monitor (n.)", th: "เครื่องเฝ้าสังเกต", ex: "The monitor showed a stable heart rate.", ex_th: "เครื่องเฝ้าสังเกตแสดงอัตราการเต้นของหัวใจที่คงที่" },
  { en: "Anxiety (n.)", th: "ความวิตกกังวล", ex: "Public speaking often causes great anxiety.", ex_th: "การพูดในที่สาธารณะมักทำให้เกิดความวิตกกังวลอย่างมาก" },
  { en: "Treatment (n.)", th: "การรักษา", ex: "The doctor recommended a new treatment for the illness.", ex_th: "แพทย์แนะนำวิธีการรักษาแบบใหม่สำหรับอาการป่วยนี้" },
  { en: "State (n.)", th: "สถานะ", ex: "The economy is in a state of rapid growth.", ex_th: "เศรษฐกิจกำลังอยู่ในสถานะของการเติบโตอย่างรวดเร็ว" },
  { en: "Faith (n.)", th: "ศรัทธา", ex: "She never lost faith in her team.", ex_th: "เธอไม่เคยสูญเสียศรัทธาในทีมของเธอเลย" },
  { en: "Infection (n.)", th: "การติดเชื้อ", ex: "The doctor prescribed antibiotics to fight the infection.", ex_th: "แพทย์สั่งยาปฏิชีวนะเพื่อต่อสู้กับการติดเชื้อ" },
  { en: "Factor (n.)", th: "ปัจจัย", ex: "Price is a key factor in our decision-making.", ex_th: "ราคาเป็นปัจจัยสำคัญในการตัดสินใจของเรา" },
  { en: "Needle (n.)", th: "เข็มฉีดยา", ex: "She felt a slight pinch from the needle.", ex_th: "เธอรู้สึกเจ็บจี๊ดเล็กน้อยจากเข็มฉีดยา" },
  { en: "Expectation (n.)", th: "ความคาดหวัง", ex: "The service exceeded my expectations.", ex_th: "บริการนี้เหนือกว่าความคาดหวังของฉันมาก" },
  { en: "Strength (n.)", th: "ความแข็งแรง/จุดแข็ง", ex: "His greatest strength is his ability to stay calm.", ex_th: "จุดแข็งที่สุดของเขาคือความสามารถในการสงบสติอารมณ์" },
  { en: "Institution (n.)", th: "สถาบัน", ex: "The university is a highly respected institution.", ex_th: "มหาวิทยาลัยแห่งนี้เป็นสถาบันที่ได้รับความนับถืออย่างสูง" },
  { en: "Capable (adj. -> N.)", th: "ที่สามารถทำได้ (ความสามารถ)", ex: "She is capable of leading the team to success.", ex_th: "เธอมีความสามารถในการนำทีมไปสู่ความสำเร็จ" },
  { en: "Behalf (n.)", th: "ในนามของ/ตัวแทน", ex: "I am writing on behalf of the entire company.", ex_th: "ฉันกำลังเขียนในนามของบริษัททั้งหมด" },
  { en: "Association (n.)", th: "สมาคม/การรวมกลุ่ม", ex: "The association aims to support local businesses.", ex_th: "สมาคมนี้มีจุดมุ่งหมายเพื่อสนับสนุนธุรกิจในท้องถิ่น" },
  { en: "Award (n.)", th: "รางวัล", ex: "She received an award for her outstanding performance.", ex_th: "เธอได้รับรางวัลสำหรับผลงานที่โดดเด่นของเธอ" },
  { en: "Weakness (n.)", th: "ความอ่อนแอ/จุดอ่อน", ex: "Being too honest can be a weakness in negotiations.", ex_th: "การซื่อสัตย์เกินไปอาจเป็นจุดอ่อนในการเจรจา" },
  { en: "Intention (n.)", th: "ความตั้งใจ/เจตนา", ex: "I have no intention of causing any trouble.", ex_th: "ฉันไม่มีเจตนาที่จะก่อให้เกิดปัญหาใดๆ" },
  { en: "Circumstance (n.)", th: "สถานการณ์/สภาพแวดล้อม", ex: "Under no circumstance should you open that door.", ex_th: "ไม่ว่าสถานการณ์ใดก็ตาม คุณไม่ควรเปิดประตูนั้น" },
  { en: "Selection (n.)", th: "การคัดเลือก", ex: "The store has a wide selection of imported chocolates.", ex_th: "ร้านมีช็อกโกแลตนำเข้าให้เลือกมากมาย" },
  { en: "Relief (n.)", th: "ความโล่งอก/การผ่อนคลาย", ex: "He felt a huge relief after passing the exam.", ex_th: "เขารู้สึกโล่งอกอย่างมากหลังจากสอบผ่าน" },
  { en: "Combination (n.)", th: "การผสมผสาน/การรวมกัน", ex: "Success is a combination of hard work and luck.", ex_th: "ความสำเร็จคือการผสมผสานระหว่างการทำงานหนักและโชค" },
  { en: "Reputation (n.)", th: "ชื่อเสียง", ex: "The company has a good reputation for customer service.", ex_th: "บริษัทมีชื่อเสียงที่ดีในด้านการบริการลูกค้า" },
  { en: "Perspective (n.)", th: "มุมมอง/ทัศนคติ", ex: "Try to see the situation from her perspective.", ex_th: "ลองมองสถานการณ์จากมุมมองของเธอดู" },
  { en: "Pirate (n.)", th: "โจรสลัด", ex: "The pirates hid their treasure on a remote island.", ex_th: "พวกโจรสลัดซ่อนสมบัติของพวกเขาไว้บนเกาะที่ห่างไกล" },
  { en: "Feature (n.)", th: "คุณลักษณะ/หน้าตา", ex: "The phone's best feature is its long battery life.", ex_th: "คุณลักษณะที่ดีที่สุดของโทรศัพท์คืออายุการใช้งานแบตเตอรี่ที่ยาวนาน" },
  { en: "Shipwreck (n.)", th: "ซากเรือแตก", ex: "Divers discovered an ancient shipwreck in the bay.", ex_th: "นักดำน้ำค้นพบซากเรือแตกโบราณในอ่าว" },
  { en: "Destination (n.)", th: "จุดหมายปลายทาง", ex: "What is your final destination, sir?", ex_th: "จุดหมายปลายทางสุดท้ายของคุณคือที่ไหนครับ" },
  { en: "Voyage (n.)", th: "การเดินทางไกล", ex: "The voyage from England to Australia took many months.", ex_th: "การเดินทางไกลจากอังกฤษไปออสเตรเลียใช้เวลาหลายเดือน" },
  { en: "Port (n.)", th: "ท่าเรือ", ex: "The ship will dock at the port of Singapore.", ex_th: "เรือจะเทียบท่าที่ท่าเรือของสิงคโปร์" },
  { en: "Potential (n.)", th: "ศักยภาพ", ex: "She has the potential to become a great leader.", ex_th: "เธอมีศักยภาพที่จะเป็นผู้นำที่ยิ่งใหญ่" },

  // กลุ่มคำคุณศัพท์ (Adjectives)
  { en: "Crucial (adj.)", th: "สำคัญยิ่ง", ex: "Time is a crucial factor in this experiment.", ex_th: "เวลาเป็นปัจจัยที่สำคัญยิ่งในการทดลองนี้" },
  { en: "Conventional (adj.)", th: "ตามแบบแผน", ex: "She prefers conventional methods of teaching.", ex_th: "เธอชอบวิธีการสอนตามแบบแผนเดิม" },
  { en: "Gradual (adj.)", th: "ค่อยเป็นค่อยไป", ex: "We saw a gradual improvement in his grades.", ex_th: "เราเห็นการพัฒนาที่เป็นไปอย่างค่อยเป็นค่อยไปในเกรดของเขา" },
  { en: "Practical (adj.)", th: "ได้ผลจริง/ใช้ได้จริง", ex: "This plan is practical for our budget.", ex_th: "แผนนี้เป็นแผนที่ได้ผลจริงสำหรับงบประมาณของเรา" },
  { en: "Aware (adj.)", th: "ตระหนัก", ex: "Everyone should be aware of the safety rules.", ex_th: "ทุกคนควรตระหนักถึงกฎความปลอดภัย" },
  { en: "Valid (adj.)", th: "ถูกต้อง", ex: "Your argument is perfectly valid.", ex_th: "ข้อโต้แย้งของคุณถูกต้องอย่างสมบูรณ์" },
  { en: "Medical (adj.)", th: "ทางการแพทย์", ex: "He is seeking medical advice for his back pain.", ex_th: "เขากำลังขอคำแนะนำทางการแพทย์สำหรับอาการปวดหลัง" },
  { en: "Potential (adj.)", th: "ที่มีศักยภาพ", ex: "The new software has great potential for growth.", ex_th: "ซอฟต์แวร์ใหม่นี้มีศักยภาพที่ยอดเยี่ยมในการเติบโต" },
  { en: "Massive (adj.)", th: "มหึมา", ex: "The storm caused massive damage to the city.", ex_th: "พายุสร้างความเสียหายอันมหึมาให้กับเมือง" },
  { en: "Artificial (adj.)", th: "เทียม", ex: "The athlete uses an artificial limb.", ex_th: "นักกีฬาคนนั้นใช้แขนขาเทียม" },
  { en: "Poisonous (adj.)", th: "เป็นพิษ", ex: "Some species of snakes are highly poisonous.", ex_th: "งูบางสายพันธุ์มีพิษร้ายแรงมาก" },
  { en: "Competitive (adj.)", th: "เกี่ยวกับการแข่งขัน/ชอบเอาชนะ", ex: "Our prices are very competitive in the market.", ex_th: "ราคาของเราสามารถแข่งขันได้ดีมากในตลาด" },
  { en: "Tough (adj.)", th: "ยอดเยี่ยม/ยากลำบาก/ทนทาน", ex: "The exam was really tough, but I think I passed.", ex_th: "ข้อสอบนั้นยากลำบากจริงๆ แต่ฉันคิดว่าฉันสอบผ่าน" },
  { en: "Sufficient (adj.)", th: "เพียงพอ", ex: "Do we have sufficient evidence to prove his guilt?", ex_th: "เรามีหลักฐานเพียงพอที่จะพิสูจน์ความผิดของเขาหรือไม่" },
  { en: "Deliberate (adj.)", th: "เจตนา/ตั้งใจ", ex: "It was a deliberate act to mislead the public.", ex_th: "มันเป็นการกระทำที่เจตนาเพื่อทำให้สาธารณชนเข้าใจผิด" },
  { en: "Outstanding (adj.)", th: "โดดเด่น", ex: "He is an outstanding student with great potential.", ex_th: "เขาเป็นนักเรียนที่โดดเด่นและมีศักยภาพที่ยอดเยี่ยม" },
  { en: "Overall (adj.)", th: "ทั้งหมด/ภาพรวม", ex: "The overall performance of the team was impressive.", ex_th: "ผลงานโดยรวมของทีมน่าประทับใจมาก" },
  { en: "Ideal (adj.)", th: "อุดมคติ/ดีเลิศ", ex: "This location is ideal for our new restaurant.", ex_th: "ทำเลนี้ดีเลิศสำหรับร้านอาหารใหม่ของเรา" },
  { en: "Suspicious (adj.)", th: "น่าสงสัย/ระแวง", ex: "The police found the man's behavior very suspicious.", ex_th: "ตำรวจพบว่าพฤติกรรมของผู้ชายคนนั้นน่าสงสัยอย่างมาก" },
  { en: "Proud (adj.)", th: "ภูมิใจ", ex: "I am so proud of your achievements this year.", ex_th: "ฉันภูมิใจในความสำเร็จของคุณในปีนี้มาก" },
  { en: "Extensive (adj.)", th: "กว้างขวาง/ครอบคลุม", ex: "He has an extensive collection of rare books.", ex_th: "เขามีคอลเลกชันหนังสือหายากที่กว้างขวาง" },
  { en: "Instant (adj.)", th: "ทันทีทันใด", ex: "The video went viral and brought her instant fame.", ex_th: "วิดีโอนั้นเป็นไวรัลและนำชื่อเสียงมาให้เธออย่างทันทีทันใด" },
  { en: "Attractive (adj.)", th: "ดึงดูดใจ/มีเสน่ห์", ex: "The salary package is very attractive for fresh graduates.", ex_th: "แพ็คเกจเงินเดือนนั้นดึงดูดใจมากสำหรับนักศึกษาจบใหม่" },
  { en: "Stunning (adj.)", th: "สวยงามตระการตา/น่าทึ่ง", ex: "The view from the mountain was absolutely stunning.", ex_th: "วิวจากบนภูเขานั้นสวยงามตระการตาอย่างยิ่ง" },
  { en: "Remarkable (adj.)", th: "น่าทึ่ง/โดดเด่น", ex: "Her recovery from the injury was remarkable.", ex_th: "การฟื้นตัวของเธอจากอาการบาดเจ็บนั้นน่าทึ่งมาก" },
  { en: "Dreadful (adj.)", th: "น่ากลัว/แย่มาก", ex: "The weather today is dreadful; let's stay inside.", ex_th: "วันนี้อากาศแย่มาก เราอยู่ข้างในกันเถอะ" },
  { en: "Exotic (adj.)", th: "แปลกตา/มาจากต่างประเทศ", ex: "The garden is full of exotic flowers from Asia.", ex_th: "สวนเต็มไปด้วยดอกไม้แปลกตาจากเอเชีย" },
  { en: "Astonishing (adj.)", th: "น่าแปลกใจมาก/น่าทึ่ง", ex: "His knowledge of history is truly astonishing.", ex_th: "ความรู้ด้านประวัติศาสตร์ของเขาน่าทึ่งอย่างแท้จริง" },
  { en: "Priceless (adj.)", th: "ล้ำค่าจนประเมินค่าไม่ได้", ex: "The museum contains many priceless works of art.", ex_th: "พิพิธภัณฑ์มีงานศิลปะล้ำค่าจำนวนมาก" },
  { en: "Unsophisticated (adj.)", th: "ซื่อๆ/ไม่ซับซ้อน", ex: "The technology is quite unsophisticated but it works well.", ex_th: "เทคโนโลยีนั้นค่อนข้างไม่ซับซ้อนแต่มันทำงานได้ดี" },
  { en: "Tremendous (adj.)", th: "ใหญ่โตมาก/ยอดเยี่ยมมาก", ex: "The project required a tremendous amount of effort.", ex_th: "โปรเจกต์นี้ต้องใช้ความพยายามอย่างใหญ่โตมาก" },
  { en: "Insignificant (adj.)", th: "ไม่สำคัญ/เล็กน้อย", ex: "Don't worry about insignificant details.", ex_th: "อย่ากังวลกับรายละเอียดที่ไม่สำคัญ" },
  { en: "Truly (adj.)", th: "อย่างแท้จริง", ex: "It was a truly unforgettable experience.", ex_th: "มันเป็นประสบการณ์ที่ยากจะลืมเลือนอย่างแท้จริง" },

  // กลุ่มคำวิเศษณ์ (Adverbs)
  { en: "Eventually (adv.)", th: "ในตอนท้าย", ex: "He eventually realized his mistake.", ex_th: "ในตอนท้ายเขาก็ตระหนักถึงความผิดพลาดของตัวเอง" },
  { en: "Initially (adv.)", th: "ในตอนแรก", ex: "Initially, I thought the task was impossible.", ex_th: "ในตอนแรกฉันคิดว่างานนี้เป็นไปไม่ได้" },
  { en: "Overall (adv.)", th: "โดยรวม/ภาพรวม", ex: "Overall, the trip was a great success.", ex_th: "โดยรวมแล้วการเดินทางนั้นประสบความสำเร็จอย่างมาก" },
  { en: "Quite (adv.)", th: "ค่อนข้างมาก", ex: "The movie was quite interesting; I recommend it.", ex_th: "หนังเรื่องนั้นค่อนข้างน่าสนใจ ฉันแนะนำเลย" }
];
